USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA CONSUMPTION_SCH;

---------------------------------------------------------------------
-- YEARLY REVENUE KPIs
---------------------------------------------------------------------
CREATE OR REPLACE VIEW CONSUMPTION_SCH.VW_YEARLY_REVENUE_KPIS AS
WITH ORDER_TOTALS AS (
    SELECT
        ORDER_ID,
        SUM(SUBTOTAL) AS ORDER_TOTAL
    FROM CONSUMPTION_SCH.ORDER_ITEM_FACT
    WHERE DELIVERY_STATUS = 'Delivered'
    GROUP BY ORDER_ID
)
SELECT
    d.YEAR AS YEAR,
    SUM(f.SUBTOTAL) AS TOTAL_REVENUE,
    COUNT(DISTINCT f.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(f.SUBTOTAL) / COUNT(DISTINCT f.ORDER_ID), 2) AS AVG_REVENUE_PER_ORDER,
    ROUND(SUM(f.SUBTOTAL) / COUNT(f.ORDER_ITEM_ID), 2) AS AVG_REVENUE_PER_ITEM,
    MAX(o.ORDER_TOTAL) AS MAX_ORDER_VALUE
FROM CONSUMPTION_SCH.ORDER_ITEM_FACT f
JOIN ORDER_TOTALS o
    ON f.ORDER_ID = o.ORDER_ID
JOIN CONSUMPTION_SCH.DATE_DIM d
    ON f.ORDER_DATE_DIM_KEY = d.DATE_DIM_HK
WHERE f.DELIVERY_STATUS = 'Delivered'
GROUP BY d.YEAR
ORDER BY d.YEAR;

---------------------------------------------------------------------
-- MONTHLY REVENUE KPIs
---------------------------------------------------------------------
CREATE OR REPLACE VIEW CONSUMPTION_SCH.VW_MONTHLY_REVENUE_KPIS AS
WITH ORDER_TOTALS AS (
    SELECT
        ORDER_ID,
        SUM(SUBTOTAL) AS ORDER_TOTAL
    FROM CONSUMPTION_SCH.ORDER_ITEM_FACT
    WHERE DELIVERY_STATUS = 'Delivered'
    GROUP BY ORDER_ID
)
SELECT
    d.YEAR AS YEAR,
    d.MONTH AS MONTH,
    SUM(f.SUBTOTAL) AS TOTAL_REVENUE,
    COUNT(DISTINCT f.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(f.SUBTOTAL) / COUNT(DISTINCT f.ORDER_ID), 2) AS AVG_REVENUE_PER_ORDER,
    ROUND(SUM(f.SUBTOTAL) / COUNT(f.ORDER_ITEM_ID), 2) AS AVG_REVENUE_PER_ITEM,
    MAX(o.ORDER_TOTAL) AS MAX_ORDER_VALUE
FROM CONSUMPTION_SCH.ORDER_ITEM_FACT f
JOIN ORDER_TOTALS o
    ON f.ORDER_ID = o.ORDER_ID
JOIN CONSUMPTION_SCH.DATE_DIM d
    ON f.ORDER_DATE_DIM_KEY = d.DATE_DIM_HK
WHERE f.DELIVERY_STATUS = 'Delivered'
GROUP BY d.YEAR, d.MONTH
ORDER BY d.YEAR, d.MONTH;

---------------------------------------------------------------------
-- DAILY REVENUE KPIs (CALENDAR DAY)
---------------------------------------------------------------------
CREATE OR REPLACE VIEW CONSUMPTION_SCH.VW_DAILY_REVENUE_KPIS AS
WITH ORDER_TOTALS AS (
    SELECT
        ORDER_ID,
        SUM(SUBTOTAL) AS ORDER_TOTAL
    FROM CONSUMPTION_SCH.ORDER_ITEM_FACT
    WHERE DELIVERY_STATUS = 'Delivered'
    GROUP BY ORDER_ID
)
SELECT
    d.YEAR AS YEAR,
    d.MONTH AS MONTH,
    d.DAY_OF_THE_MONTH AS DAY,
    SUM(f.SUBTOTAL) AS TOTAL_REVENUE,
    COUNT(DISTINCT f.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(f.SUBTOTAL) / COUNT(DISTINCT f.ORDER_ID), 2) AS AVG_REVENUE_PER_ORDER,
    ROUND(SUM(f.SUBTOTAL) / COUNT(f.ORDER_ITEM_ID), 2) AS AVG_REVENUE_PER_ITEM,
    MAX(o.ORDER_TOTAL) AS MAX_ORDER_VALUE
FROM CONSUMPTION_SCH.ORDER_ITEM_FACT f
JOIN ORDER_TOTALS o
    ON f.ORDER_ID = o.ORDER_ID
JOIN CONSUMPTION_SCH.DATE_DIM d
    ON f.ORDER_DATE_DIM_KEY = d.DATE_DIM_HK
WHERE f.DELIVERY_STATUS = 'Delivered'
GROUP BY d.YEAR, d.MONTH, d.DAY_OF_THE_MONTH
ORDER BY d.YEAR, d.MONTH, d.DAY_OF_THE_MONTH;

---------------------------------------------------------------------
-- DAY OF WEEK REVENUE KPIs (PATTERN ANALYSIS)
---------------------------------------------------------------------
CREATE OR REPLACE VIEW CONSUMPTION_SCH.VW_DAY_OF_WEEK_REVENUE_KPIS AS
WITH ORDER_TOTALS AS (
    SELECT
        ORDER_ID,
        SUM(SUBTOTAL) AS ORDER_TOTAL
    FROM CONSUMPTION_SCH.ORDER_ITEM_FACT
    WHERE DELIVERY_STATUS = 'Delivered'
    GROUP BY ORDER_ID
)
SELECT
    d.YEAR AS YEAR,
    d.MONTH AS MONTH,
    d.DAY_NAME AS DAY_NAME,
    SUM(f.SUBTOTAL) AS TOTAL_REVENUE,
    COUNT(DISTINCT f.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(f.SUBTOTAL) / COUNT(DISTINCT f.ORDER_ID), 2) AS AVG_REVENUE_PER_ORDER,
    ROUND(SUM(f.SUBTOTAL) / COUNT(f.ORDER_ITEM_ID), 2) AS AVG_REVENUE_PER_ITEM,
    MAX(o.ORDER_TOTAL) AS MAX_ORDER_VALUE
FROM CONSUMPTION_SCH.ORDER_ITEM_FACT f
JOIN ORDER_TOTALS o
    ON f.ORDER_ID = o.ORDER_ID
JOIN CONSUMPTION_SCH.DATE_DIM d
    ON f.ORDER_DATE_DIM_KEY = d.DATE_DIM_HK
WHERE f.DELIVERY_STATUS = 'Delivered'
GROUP BY d.YEAR, d.MONTH, d.DAY_NAME
ORDER BY d.YEAR, d.MONTH, d.DAY_NAME;

---------------------------------------------------------------------
-- MONTHLY REVENUE BY RESTAURANT
---------------------------------------------------------------------
CREATE OR REPLACE VIEW CONSUMPTION_SCH.VW_MONTHLY_REVENUE_BY_RESTAURANT AS
WITH ORDER_TOTALS AS (
    SELECT
        ORDER_ID,
        SUM(SUBTOTAL) AS ORDER_TOTAL
    FROM CONSUMPTION_SCH.ORDER_ITEM_FACT
    WHERE DELIVERY_STATUS = 'Delivered'
    GROUP BY ORDER_ID
)
SELECT
    d.YEAR AS YEAR,
    d.MONTH AS MONTH,
    r.NAME AS RESTAURANT_NAME,
    SUM(f.SUBTOTAL) AS TOTAL_REVENUE,
    COUNT(DISTINCT f.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(SUM(f.SUBTOTAL) / COUNT(DISTINCT f.ORDER_ID), 2) AS AVG_REVENUE_PER_ORDER,
    ROUND(SUM(f.SUBTOTAL) / COUNT(f.ORDER_ITEM_ID), 2) AS AVG_REVENUE_PER_ITEM,
    MAX(o.ORDER_TOTAL) AS MAX_ORDER_VALUE
FROM CONSUMPTION_SCH.ORDER_ITEM_FACT f
JOIN ORDER_TOTALS o
    ON f.ORDER_ID = o.ORDER_ID
JOIN CONSUMPTION_SCH.DATE_DIM d
    ON f.ORDER_DATE_DIM_KEY = d.DATE_DIM_HK
JOIN CONSUMPTION_SCH.RESTAURANT_DIM r
    ON f.RESTAURANT_DIM_KEY = r.RESTAURANT_HK
WHERE f.DELIVERY_STATUS = 'Delivered'
GROUP BY d.YEAR, d.MONTH, r.NAME
ORDER BY d.YEAR, d.MONTH, r.NAME;




