USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;
USE SCHEMA CONSUMPTION_SCH;

/* =========================================================
   FACT TABLE
   ========================================================= */
CREATE OR REPLACE TABLE CONSUMPTION_SCH.ORDER_ITEM_FACT (
    ORDER_ITEM_FACT_SK NUMBER AUTOINCREMENT COMMENT 'Surrogate Key (EDW)',
    ORDER_ITEM_ID NUMBER COMMENT 'Order Item ID (Source)',
    ORDER_ID NUMBER COMMENT 'Order ID (Source)',

    CUSTOMER_DIM_KEY NUMBER COMMENT 'FK to CUSTOMER_DIM',
    CUSTOMER_ADDRESS_DIM_KEY NUMBER COMMENT 'FK to CUSTOMER_ADDRESS_DIM',
    RESTAURANT_DIM_KEY NUMBER COMMENT 'FK to RESTAURANT_DIM',
    RESTAURANT_LOCATION_DIM_KEY NUMBER COMMENT 'FK to RESTAURANT_LOCATION_DIM',
    MENU_DIM_KEY NUMBER COMMENT 'FK to MENU_DIM',
    DELIVERY_AGENT_DIM_KEY NUMBER COMMENT 'FK to DELIVERY_AGENT_DIM',
    ORDER_DATE_DIM_KEY NUMBER COMMENT 'FK to DATE_DIM',

    QUANTITY NUMBER COMMENT 'Item quantity',
    PRICE NUMBER(10,2) COMMENT 'Item price',
    SUBTOTAL NUMBER(10,2) COMMENT 'Item subtotal',

    DELIVERY_STATUS STRING COMMENT 'Delivery status',
    ESTIMATED_TIME STRING COMMENT 'Estimated delivery time'
)
COMMENT = 'Order item fact table at item grain';

/* =========================================================
   FACT LOAD (INCREMENTAL, STREAM‑DRIVEN)
   ========================================================= */
MERGE INTO CONSUMPTION_SCH.ORDER_ITEM_FACT AS target
USING (
    SELECT
        oi.ORDER_ITEM_ID,
        oi.ORDER_ID_FK AS ORDER_ID,

        c.CUSTOMER_HK AS CUSTOMER_DIM_KEY,
        ca.CUSTOMER_ADDRESS_HK AS CUSTOMER_ADDRESS_DIM_KEY,
        r.RESTAURANT_HK AS RESTAURANT_DIM_KEY,
        rl.RESTAURANT_LOCATION_HK AS RESTAURANT_LOCATION_DIM_KEY,
        m.MENU_DIM_HK AS MENU_DIM_KEY,
        da.DELIVERY_AGENT_HK AS DELIVERY_AGENT_DIM_KEY,
        dd.DATE_DIM_HK AS ORDER_DATE_DIM_KEY,

        oi.QUANTITY,
        oi.PRICE,
        oi.SUBTOTAL,

        d.DELIVERY_STATUS,
        d.ESTIMATED_TIME

    FROM CLEAN_SCH.ORDER_ITEM_STM oi              

    JOIN CLEAN_SCH.ORDERS o
        ON oi.ORDER_ID_FK = o.ORDER_ID

    LEFT JOIN CLEAN_SCH.DELIVERY d
        ON o.ORDER_ID = d.ORDER_ID_FK

    JOIN CONSUMPTION_SCH.CUSTOMER_DIM c
        ON o.CUSTOMER_ID_FK = c.CUSTOMER_ID
       AND c.IS_CURRENT = TRUE

    JOIN CONSUMPTION_SCH.CUSTOMER_ADDRESS_DIM ca
        ON ca.CUSTOMER_ID_FK = c.CUSTOMER_ID
       AND ca.IS_CURRENT = TRUE

    JOIN CONSUMPTION_SCH.RESTAURANT_DIM r
        ON o.RESTAURANT_ID_FK = r.RESTAURANT_ID
       AND r.IS_CURRENT = TRUE

    JOIN CONSUMPTION_SCH.RESTAURANT_LOCATION_DIM rl
        ON r.LOCATION_ID_FK = rl.LOCATION_ID
       AND rl.CURRENT_FLAG = TRUE

    JOIN CONSUMPTION_SCH.MENU_DIM m
        ON oi.MENU_ID_FK = m.MENU_ID
       AND m.IS_CURRENT = TRUE

    LEFT JOIN CONSUMPTION_SCH.DELIVERY_AGENT_DIM da
        ON d.DELIVERY_AGENT_ID_FK = da.DELIVERY_AGENT_ID
       AND da.IS_CURRENT = TRUE

    JOIN CONSUMPTION_SCH.DATE_DIM dd
        ON dd.CALENDAR_DATE = DATE(o.ORDER_DATE)
) source
ON target.ORDER_ITEM_ID = source.ORDER_ITEM_ID
   AND target.ORDER_ID = source.ORDER_ID

WHEN MATCHED THEN
UPDATE SET
    CUSTOMER_DIM_KEY = source.CUSTOMER_DIM_KEY,
    CUSTOMER_ADDRESS_DIM_KEY = source.CUSTOMER_ADDRESS_DIM_KEY,
    RESTAURANT_DIM_KEY = source.RESTAURANT_DIM_KEY,
    RESTAURANT_LOCATION_DIM_KEY = source.RESTAURANT_LOCATION_DIM_KEY,
    MENU_DIM_KEY = source.MENU_DIM_KEY,
    DELIVERY_AGENT_DIM_KEY = source.DELIVERY_AGENT_DIM_KEY,
    ORDER_DATE_DIM_KEY = source.ORDER_DATE_DIM_KEY,
    QUANTITY = source.QUANTITY,
    PRICE = source.PRICE,
    SUBTOTAL = source.SUBTOTAL,
    DELIVERY_STATUS = source.DELIVERY_STATUS,
    ESTIMATED_TIME = source.ESTIMATED_TIME

WHEN NOT MATCHED THEN
INSERT (
    ORDER_ITEM_ID,
    ORDER_ID,
    CUSTOMER_DIM_KEY,
    CUSTOMER_ADDRESS_DIM_KEY,
    RESTAURANT_DIM_KEY,
    RESTAURANT_LOCATION_DIM_KEY,
    MENU_DIM_KEY,
    DELIVERY_AGENT_DIM_KEY,
    ORDER_DATE_DIM_KEY,
    QUANTITY,
    PRICE,
    SUBTOTAL,
    DELIVERY_STATUS,
    ESTIMATED_TIME
)
VALUES (
    source.ORDER_ITEM_ID,
    source.ORDER_ID,
    source.CUSTOMER_DIM_KEY,
    source.CUSTOMER_ADDRESS_DIM_KEY,
    source.RESTAURANT_DIM_KEY,
    source.RESTAURANT_LOCATION_DIM_KEY,
    source.MENU_DIM_KEY,
    source.DELIVERY_AGENT_DIM_KEY,
    source.ORDER_DATE_DIM_KEY,
    source.QUANTITY,
    source.PRICE,
    source.SUBTOTAL,
    source.DELIVERY_STATUS,
    source.ESTIMATED_TIME
);



    
