USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;


CREATE OR REPLACE TABLE STAGE_SCH.CUSTOMER (
    CUSTOMERID TEXT,
    NAME TEXT,
    MOBILE TEXT WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
    EMAIL TEXT WITH TAG (COMMON.PII_POLICY_TAG = 'EMAIL'),
    LOGINBYUSING TEXT,
    GENDER TEXT WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
    DOB TEXT WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
    ANNIVERSARY TEXT,
    PREFERENCES TEXT,
    CREATEDDATE TEXT,
    MODIFIEDDATE TEXT,

    _STG_FILE_NAME TEXT,
    _STG_FILE_LOAD_TS TIMESTAMP,
    _STG_FILE_MD5 TEXT,
    _COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE STREAM STAGE_SCH.CUSTOMER_STM_DQ
ON TABLE STAGE_SCH.CUSTOMER
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM STAGE_SCH.CUSTOMER_STM_TRANSFORM
ON TABLE STAGE_SCH.CUSTOMER
APPEND_ONLY = TRUE;


CREATE OR REPLACE TABLE STAGE_SCH.CUSTOMER_DQ_ERROR (
    CUSTOMERID TEXT,
    NAME TEXT,
    MOBILE TEXT,
    EMAIL TEXT,
    ERROR_REASON TEXT,
    _STG_FILE_NAME TEXT,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE OR REPLACE PIPE STAGE_SCH.CUSTOMER_PIPE
AS
COPY INTO STAGE_SCH.CUSTOMER
FROM (
    SELECT
        t.$1::TEXT,
        t.$2::TEXT,
        t.$3::TEXT,
        t.$4::TEXT,
        t.$5::TEXT,
        t.$6::TEXT,
        t.$7::TEXT,
        t.$8::TEXT,
        t.$9::TEXT,
        t.$10::TEXT,
        t.$11::TEXT,
        METADATA$FILENAME,
        METADATA$FILE_LAST_MODIFIED,
        METADATA$FILE_CONTENT_KEY,
        CURRENT_TIMESTAMP
    FROM @STAGE_SCH.CSV_STG/CUSTOMERS t
)
FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT')
ON_ERROR = 'CONTINUE';


CREATE OR REPLACE TABLE CLEAN_SCH.CUSTOMER (
    CUSTOMER_SK NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID STRING NOT NULL,
    NAME STRING(100) NOT NULL,
    MOBILE STRING(15) WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
    EMAIL STRING(100) WITH TAG (COMMON.PII_POLICY_TAG = 'EMAIL'),
    LOGIN_BY_USING STRING(50),
    GENDER STRING(10) WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
    DOB DATE WITH TAG (COMMON.PII_POLICY_TAG = 'PII'),
    ANNIVERSARY DATE,
    PREFERENCES STRING,
    CREATED_DT TIMESTAMP_TZ,
    MODIFIED_DT TIMESTAMP_TZ,

    _STG_FILE_NAME STRING,
    _STG_FILE_LOAD_TS TIMESTAMP_NTZ,
    _STG_FILE_MD5 STRING,
    _COPY_DATA_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);



CREATE OR REPLACE STREAM CLEAN_SCH.CUSTOMER_STM
ON TABLE CLEAN_SCH.CUSTOMER;



CREATE OR REPLACE TASK STAGE_SCH.CUSTOMER_DQ_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.CUSTOMER_STM_DQ')
AS
INSERT INTO STAGE_SCH.CUSTOMER_DQ_ERROR
SELECT
    CUSTOMERID,
    NAME,
    MOBILE,
    EMAIL,
    CASE
        WHEN CUSTOMERID IS NULL THEN 'CUSTOMERID NULL'
        WHEN NAME IS NULL THEN 'NAME NULL'
        WHEN EMAIL IS NULL THEN 'EMAIL NULL'
    END,
    _STG_FILE_NAME,
    CURRENT_TIMESTAMP
FROM STAGE_SCH.CUSTOMER_STM_DQ
WHERE
    CUSTOMERID IS NULL
    OR NAME IS NULL
    OR EMAIL IS NULL;



    CREATE OR REPLACE TASK STAGE_SCH.CUSTOMER_TRANSFORM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.CUSTOMER_STM_TRANSFORM')
AS
MERGE INTO CLEAN_SCH.CUSTOMER AS target
USING (
    SELECT
        CUSTOMERID AS CUSTOMER_ID,
        NAME,
        MOBILE,
        EMAIL,
        LOGINBYUSING AS LOGIN_BY_USING,
        GENDER,
        TRY_TO_DATE(DOB,'YYYY-MM-DD') AS DOB,
        TRY_TO_DATE(ANNIVERSARY,'YYYY-MM-DD') AS ANNIVERSARY,
        PREFERENCES,
        TRY_TO_TIMESTAMP_TZ(CREATEDDATE,'YYYY-MM-DD HH24:MI:SS') AS CREATED_DT,
        TRY_TO_TIMESTAMP_TZ(MODIFIEDDATE,'YYYY-MM-DD HH24:MI:SS') AS MODIFIED_DT,
        _STG_FILE_NAME,
        _STG_FILE_LOAD_TS,
        _STG_FILE_MD5,
        CURRENT_TIMESTAMP AS _COPY_DATA_TS
    FROM STAGE_SCH.CUSTOMER_STM_TRANSFORM
    WHERE CUSTOMERID IS NOT NULL
) source
ON target.CUSTOMER_ID = source.CUSTOMER_ID

WHEN MATCHED THEN UPDATE SET
    target.NAME = source.NAME,
    target.MOBILE = source.MOBILE,
    target.EMAIL = source.EMAIL,
    target.LOGIN_BY_USING = source.LOGIN_BY_USING,
    target.GENDER = source.GENDER,
    target.DOB = source.DOB,
    target.ANNIVERSARY = source.ANNIVERSARY,
    target.PREFERENCES = source.PREFERENCES,
    target.MODIFIED_DT = source.MODIFIED_DT

WHEN NOT MATCHED THEN INSERT (
    CUSTOMER_ID, NAME, MOBILE, EMAIL, LOGIN_BY_USING,
    GENDER, DOB, ANNIVERSARY, PREFERENCES,
    CREATED_DT, MODIFIED_DT,
    _STG_FILE_NAME, _STG_FILE_LOAD_TS, _STG_FILE_MD5, _COPY_DATA_TS
)
VALUES (
    source.CUSTOMER_ID, source.NAME, source.MOBILE, source.EMAIL,
    source.LOGIN_BY_USING, source.GENDER, source.DOB,
    source.ANNIVERSARY, source.PREFERENCES,
    source.CREATED_DT, source.MODIFIED_DT,
    source._STG_FILE_NAME, source._STG_FILE_LOAD_TS,
    source._STG_FILE_MD5, source._COPY_DATA_TS
);



CREATE OR REPLACE TABLE CONSUMPTION_SCH.CUSTOMER_DIM (
    CUSTOMER_HK NUMBER PRIMARY KEY,              
    CUSTOMER_ID STRING NOT NULL,                                 
    NAME STRING(100) NOT NULL,                                   
    MOBILE STRING(15) WITH TAG (common.pii_policy_tag = 'PII'),                                           
    EMAIL STRING(100) WITH TAG (common.pii_policy_tag = 'EMAIL'),                                           
    LOGIN_BY_USING STRING(50),                                  
    GENDER STRING(10) WITH TAG (common.pii_policy_tag = 'PII'),                                          
    DOB DATE WITH TAG (common.pii_policy_tag = 'PII'),                                                   
    ANNIVERSARY DATE,                                            
    PREFERENCES STRING,                                          
    EFF_START_DATE TIMESTAMP_TZ,                                 
    EFF_END_DATE TIMESTAMP_TZ,                                  
    IS_CURRENT BOOLEAN  
    );

   CREATE OR REPLACE TASK CLEAN_SCH.CUSTOMER_DIM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('CLEAN_SCH.CUSTOMER_STM')
AS
MERGE INTO CONSUMPTION_SCH.CUSTOMER_DIM AS target
USING CLEAN_SCH.CUSTOMER_STM AS source
ON target.CUSTOMER_ID = source.CUSTOMER_ID
   AND target.IS_CURRENT = TRUE

WHEN MATCHED
 AND source.METADATA$ACTION = 'DELETE'
 AND source.METADATA$ISUPDATE = 'TRUE'
THEN UPDATE SET
    target.EFF_END_DATE = CURRENT_TIMESTAMP(),
    target.IS_CURRENT = FALSE

WHEN NOT MATCHED
 AND source.METADATA$ACTION = 'INSERT'
 AND source.METADATA$ISUPDATE = 'TRUE'
THEN INSERT (
    CUSTOMER_HK, CUSTOMER_ID, NAME, MOBILE, EMAIL,
    LOGIN_BY_USING, GENDER, DOB, ANNIVERSARY, PREFERENCES,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.CUSTOMER_ID, source.NAME, source.MOBILE,
        source.EMAIL, source.LOGIN_BY_USING, source.GENDER,
        source.DOB, source.ANNIVERSARY, source.PREFERENCES
    ))),
    source.CUSTOMER_ID, source.NAME, source.MOBILE, source.EMAIL,
    source.LOGIN_BY_USING, source.GENDER, source.DOB,
    source.ANNIVERSARY, source.PREFERENCES,
    CURRENT_TIMESTAMP(), NULL, TRUE
)

WHEN NOT MATCHED
 AND source.METADATA$ACTION = 'INSERT'
 AND source.METADATA$ISUPDATE = 'FALSE'
THEN INSERT (
    CUSTOMER_HK, CUSTOMER_ID, NAME, MOBILE, EMAIL,
    LOGIN_BY_USING, GENDER, DOB, ANNIVERSARY, PREFERENCES,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.CUSTOMER_ID, source.NAME, source.MOBILE,
        source.EMAIL, source.LOGIN_BY_USING, source.GENDER,
        source.DOB, source.ANNIVERSARY, source.PREFERENCES
    ))),
    source.CUSTOMER_ID, source.NAME, source.MOBILE, source.EMAIL,
    source.LOGIN_BY_USING, source.GENDER, source.DOB,
    source.ANNIVERSARY, source.PREFERENCES,
    CURRENT_TIMESTAMP(), NULL, TRUE
);

ALTER TASK STAGE_SCH.CUSTOMER_DQ_TASK RESUME;
ALTER TASK STAGE_SCH.CUSTOMER_TRANSFORM_TASK RESUME;
ALTER TASK CLEAN_SCH.CUSTOMER_DIM_TASK RESUME;

ALTER PIPE STAGE_SCH.CUSTOMER_PIPE REFRESH;





