USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;


CREATE OR REPLACE TABLE STAGE_SCH.CUSTOMERADDRESS (
    ADDRESSID TEXT,
    CUSTOMERID TEXT,
    FLATNO TEXT,
    HOUSENO TEXT,
    FLOOR TEXT,
    BUILDING TEXT,
    LANDMARK TEXT,
    LOCALITY TEXT,
    CITY TEXT,
    STATE TEXT,
    PINCODE TEXT,
    COORDINATES TEXT,
    PRIMARYFLAG TEXT,
    ADDRESSTYPE TEXT,
    CREATEDDATE TEXT,
    MODIFIEDDATE TEXT,

    _STG_FILE_NAME TEXT,
    _STG_FILE_LOAD_TS TIMESTAMP,
    _STG_FILE_MD5 TEXT,
    _COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE STREAM STAGE_SCH.CUSTOMERADDRESS_STM_DQ
ON TABLE STAGE_SCH.CUSTOMERADDRESS
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM STAGE_SCH.CUSTOMERADDRESS_STM_TRANSFORM
ON TABLE STAGE_SCH.CUSTOMERADDRESS
APPEND_ONLY = TRUE;

CREATE OR REPLACE TABLE STAGE_SCH.CUSTOMERADDRESS_DQ_ERROR (
    ADDRESSID TEXT,
    CUSTOMERID TEXT,
    CITY TEXT,
    PINCODE TEXT,
    ERROR_REASON TEXT,
    _STG_FILE_NAME TEXT,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE PIPE STAGE_SCH.CUSTOMERADDRESS_PIPE
AS
COPY INTO STAGE_SCH.CUSTOMERADDRESS
FROM (
    SELECT
        t.$1::TEXT,
        t.$2::TEXT,
        t.$3::TEXT,
        t.$4::TEXT,
        t.$5::TEXT,
        t.$6::TEXT,
        t.$7::TEXT,
        t.$8::TEXT,
        t.$9::TEXT,
        t.$10::TEXT,
        t.$11::TEXT,
        t.$12::TEXT,
        t.$13::TEXT,
        t.$14::TEXT,
        t.$15::TEXT,
        t.$16::TEXT,
        METADATA$FILENAME,
        METADATA$FILE_LAST_MODIFIED,
        METADATA$FILE_CONTENT_KEY,
        CURRENT_TIMESTAMP
    FROM @STAGE_SCH.CSV_STG/CUSTOMER-ADDRESS t
)
FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT')
ON_ERROR = 'CONTINUE';


CREATE OR REPLACE TABLE CLEAN_SCH.CUSTOMER_ADDRESS (
    CUSTOMER_ADDRESS_SK NUMBER AUTOINCREMENT PRIMARY KEY,
    ADDRESS_ID NUMBER,
    CUSTOMER_ID_FK NUMBER,
    FLAT_NO STRING,
    HOUSE_NO STRING,
    FLOOR STRING,
    BUILDING STRING,
    LANDMARK STRING,
    LOCALITY STRING,
    CITY STRING,
    STATE STRING,
    PINCODE STRING,
    COORDINATES STRING,
    PRIMARY_FLAG STRING,
    ADDRESS_TYPE STRING,
    CREATED_DATE TIMESTAMP_TZ,
    MODIFIED_DATE TIMESTAMP_TZ,

    _STG_FILE_NAME STRING,
    _STG_FILE_LOAD_TS TIMESTAMP,
    _STG_FILE_MD5 STRING,
    _COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE STREAM CLEAN_SCH.CUSTOMER_ADDRESS_STM
ON TABLE CLEAN_SCH.CUSTOMER_ADDRESS;


CREATE OR REPLACE TASK STAGE_SCH.CUSTOMERADDRESS_DQ_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.CUSTOMERADDRESS_STM_DQ')
AS
INSERT INTO STAGE_SCH.CUSTOMERADDRESS_DQ_ERROR
SELECT
    ADDRESSID,
    CUSTOMERID,
    CITY,
    PINCODE,
    CASE
        WHEN TRY_TO_NUMBER(ADDRESSID) IS NULL THEN 'INVALID ADDRESSID'
        WHEN TRY_TO_NUMBER(CUSTOMERID) IS NULL THEN 'INVALID CUSTOMERID'
        WHEN CITY IS NULL THEN 'CITY NULL'
        WHEN PINCODE IS NULL THEN 'PINCODE NULL'
    END,
    _STG_FILE_NAME,
    CURRENT_TIMESTAMP
FROM STAGE_SCH.CUSTOMERADDRESS_STM_DQ
WHERE
    TRY_TO_NUMBER(ADDRESSID) IS NULL
    OR TRY_TO_NUMBER(CUSTOMERID) IS NULL
    OR CITY IS NULL
    OR PINCODE IS NULL;


    CREATE OR REPLACE TASK STAGE_SCH.CUSTOMERADDRESS_TRANSFORM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.CUSTOMERADDRESS_STM_TRANSFORM')
AS
MERGE INTO CLEAN_SCH.CUSTOMER_ADDRESS AS target
USING (
    SELECT
        TRY_TO_NUMBER(ADDRESSID) AS ADDRESS_ID,
        TRY_TO_NUMBER(CUSTOMERID) AS CUSTOMER_ID_FK,
        FLATNO AS FLAT_NO,
        HOUSENO AS HOUSE_NO,
        FLOOR,
        BUILDING,
        LANDMARK,
        LOCALITY,
        CITY,
        STATE,
        PINCODE,
        COORDINATES,
        PRIMARYFLAG AS PRIMARY_FLAG,
        ADDRESSTYPE AS ADDRESS_TYPE,
        TRY_TO_TIMESTAMP_TZ(CREATEDDATE,'YYYY-MM-DD"T"HH24:MI:SS') AS CREATED_DATE,
        TRY_TO_TIMESTAMP_TZ(MODIFIEDDATE,'YYYY-MM-DD"T"HH24:MI:SS') AS MODIFIED_DATE,
        _STG_FILE_NAME,
        _STG_FILE_LOAD_TS,
        _STG_FILE_MD5,
        CURRENT_TIMESTAMP AS _COPY_DATA_TS
    FROM STAGE_SCH.CUSTOMERADDRESS_STM_TRANSFORM
    WHERE TRY_TO_NUMBER(ADDRESSID) IS NOT NULL
) source
ON target.ADDRESS_ID = source.ADDRESS_ID

WHEN MATCHED THEN UPDATE SET
    target.FLAT_NO = source.FLAT_NO,
    target.HOUSE_NO = source.HOUSE_NO,
    target.FLOOR = source.FLOOR,
    target.BUILDING = source.BUILDING,
    target.LANDMARK = source.LANDMARK,
    target.LOCALITY = source.LOCALITY,
    target.CITY = source.CITY,
    target.STATE = source.STATE,
    target.PINCODE = source.PINCODE,
    target.COORDINATES = source.COORDINATES,
    target.PRIMARY_FLAG = source.PRIMARY_FLAG,
    target.ADDRESS_TYPE = source.ADDRESS_TYPE,
    target.MODIFIED_DATE = source.MODIFIED_DATE

WHEN NOT MATCHED THEN INSERT (
    ADDRESS_ID, CUSTOMER_ID_FK, FLAT_NO, HOUSE_NO, FLOOR,
    BUILDING, LANDMARK, LOCALITY, CITY, STATE, PINCODE,
    COORDINATES, PRIMARY_FLAG, ADDRESS_TYPE,
    CREATED_DATE, MODIFIED_DATE,
    _STG_FILE_NAME, _STG_FILE_LOAD_TS, _STG_FILE_MD5, _COPY_DATA_TS
)
VALUES (
    source.ADDRESS_ID, source.CUSTOMER_ID_FK, source.FLAT_NO, source.HOUSE_NO,
    source.FLOOR, source.BUILDING, source.LANDMARK, source.LOCALITY,
    source.CITY, source.STATE, source.PINCODE, source.COORDINATES,
    source.PRIMARY_FLAG, source.ADDRESS_TYPE,
    source.CREATED_DATE, source.MODIFIED_DATE,
    source._STG_FILE_NAME, source._STG_FILE_LOAD_TS,
    source._STG_FILE_MD5, source._COPY_DATA_TS
);


CREATE OR REPLACE TABLE CONSUMPTION_SCH.CUSTOMER_ADDRESS_DIM (
    CUSTOMER_ADDRESS_HK NUMBER PRIMARY KEY,
    ADDRESS_ID NUMBER,
    CUSTOMER_ID_FK NUMBER,
    FLAT_NO STRING,
    HOUSE_NO STRING,
    FLOOR STRING,
    BUILDING STRING,
    LANDMARK STRING,
    LOCALITY STRING,
    CITY STRING,
    STATE STRING,
    PINCODE STRING,
    COORDINATES STRING,
    PRIMARY_FLAG STRING,
    ADDRESS_TYPE STRING,
    EFF_START_DATE TIMESTAMP_TZ,
    EFF_END_DATE TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN
);


CREATE OR REPLACE TASK CLEAN_SCH.CUSTOMER_ADDRESS_DIM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('CLEAN_SCH.CUSTOMER_ADDRESS_STM')
AS
MERGE INTO CONSUMPTION_SCH.CUSTOMER_ADDRESS_DIM AS target
USING CLEAN_SCH.CUSTOMER_ADDRESS_STM AS source
ON target.ADDRESS_ID = source.ADDRESS_ID
   AND target.IS_CURRENT = TRUE

WHEN MATCHED AND source.METADATA$ACTION = 'DELETE'
THEN UPDATE SET
    target.EFF_END_DATE = CURRENT_TIMESTAMP(),
    target.IS_CURRENT = FALSE

WHEN NOT MATCHED THEN INSERT (
    CUSTOMER_ADDRESS_HK, ADDRESS_ID, CUSTOMER_ID_FK,
    FLAT_NO, HOUSE_NO, FLOOR, BUILDING, LANDMARK,
    LOCALITY, CITY, STATE, PINCODE, COORDINATES,
    PRIMARY_FLAG, ADDRESS_TYPE,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.ADDRESS_ID, source.CUSTOMER_ID_FK,
        source.FLAT_NO, source.HOUSE_NO, source.FLOOR,
        source.BUILDING, source.LANDMARK, source.LOCALITY,
        source.CITY, source.STATE, source.PINCODE,
        source.COORDINATES, source.PRIMARY_FLAG, source.ADDRESS_TYPE
    ))),
    source.ADDRESS_ID, source.CUSTOMER_ID_FK,
    source.FLAT_NO, source.HOUSE_NO, source.FLOOR,
    source.BUILDING, source.LANDMARK, source.LOCALITY,
    source.CITY, source.STATE, source.PINCODE,
    source.COORDINATES, source.PRIMARY_FLAG, source.ADDRESS_TYPE,
    CURRENT_TIMESTAMP(), NULL, TRUE
);


ALTER TASK STAGE_SCH.CUSTOMERADDRESS_DQ_TASK RESUME;
ALTER TASK STAGE_SCH.CUSTOMERADDRESS_TRANSFORM_TASK RESUME;
ALTER TASK CLEAN_SCH.CUSTOMER_ADDRESS_DIM_TASK RESUME;

ALTER PIPE STAGE_SCH.CUSTOMERADDRESS_PIPE REFRESH;

