USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE TABLE STAGE_SCH.DELIVERY (
    DELIVERYID TEXT,
    ORDERID TEXT,
    DELIVERYAGENTID TEXT,
    DELIVERYSTATUS TEXT,
    ESTIMATEDTIME TEXT,
    ADDRESSID TEXT,
    DELIVERYDATE TEXT,
    CREATEDDATE TEXT,
    MODIFIEDDATE TEXT,

    _STG_FILE_NAME TEXT,
    _STG_FILE_LOAD_TS TIMESTAMP,
    _STG_FILE_MD5 TEXT,
    _COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE STREAM STAGE_SCH.DELIVERY_STM_DQ
ON TABLE STAGE_SCH.DELIVERY
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM STAGE_SCH.DELIVERY_STM_TRANSFORM
ON TABLE STAGE_SCH.DELIVERY
APPEND_ONLY = TRUE;


CREATE OR REPLACE TABLE STAGE_SCH.DELIVERY_DQ_ERROR (
    DELIVERYID TEXT,
    ORDERID TEXT,
    DELIVERYAGENTID TEXT,
    ADDRESSID TEXT,
    ERROR_REASON TEXT,
    _STG_FILE_NAME TEXT,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE PIPE STAGE_SCH.DELIVERY_PIPE
AS
COPY INTO STAGE_SCH.DELIVERY
FROM (
    SELECT
        t.$1::TEXT,
        t.$2::TEXT,
        t.$3::TEXT,
        t.$4::TEXT,
        t.$5::TEXT,
        t.$6::TEXT,
        t.$7::TEXT,
        t.$8::TEXT,
        t.$9::TEXT,
        METADATA$FILENAME,
        METADATA$FILE_LAST_MODIFIED,
        METADATA$FILE_CONTENT_KEY,
        CURRENT_TIMESTAMP
    FROM @STAGE_SCH.CSV_STG/DELIVERIES t
)
FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT')
ON_ERROR = 'CONTINUE';


CREATE OR REPLACE TABLE CLEAN_SCH.DELIVERY (
    DELIVERY_SK NUMBER AUTOINCREMENT PRIMARY KEY,
    DELIVERY_ID NUMBER NOT NULL,
    ORDER_ID_FK NUMBER NOT NULL,
    DELIVERY_AGENT_ID_FK NUMBER NOT NULL,
    DELIVERY_STATUS STRING,
    ESTIMATED_TIME STRING,
    CUSTOMER_ADDRESS_ID_FK NUMBER NOT NULL,
    DELIVERY_DATE TIMESTAMP_NTZ,
    CREATED_DATE TIMESTAMP_NTZ,
    MODIFIED_DATE TIMESTAMP_NTZ,

    _STG_FILE_NAME STRING,
    _STG_FILE_LOAD_TS TIMESTAMP_NTZ,
    _STG_FILE_MD5 STRING,
    _COPY_DATA_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE STREAM CLEAN_SCH.DELIVERY_STM
ON TABLE CLEAN_SCH.DELIVERY;


CREATE OR REPLACE TASK STAGE_SCH.DELIVERY_DQ_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.DELIVERY_STM_DQ')
AS
INSERT INTO STAGE_SCH.DELIVERY_DQ_ERROR
SELECT
    DELIVERYID,
    ORDERID,
    DELIVERYAGENTID,
    ADDRESSID,
    CASE
        WHEN TRY_TO_NUMBER(DELIVERYID) IS NULL THEN 'INVALID DELIVERYID'
        WHEN TRY_TO_NUMBER(ORDERID) IS NULL THEN 'INVALID ORDERID'
        WHEN TRY_TO_NUMBER(DELIVERYAGENTID) IS NULL THEN 'INVALID DELIVERYAGENTID'
        WHEN TRY_TO_NUMBER(ADDRESSID) IS NULL THEN 'INVALID ADDRESSID'
    END,
    _STG_FILE_NAME,
    CURRENT_TIMESTAMP
FROM STAGE_SCH.DELIVERY_STM_DQ
WHERE
    TRY_TO_NUMBER(DELIVERYID) IS NULL
    OR TRY_TO_NUMBER(ORDERID) IS NULL
    OR TRY_TO_NUMBER(DELIVERYAGENTID) IS NULL
    OR TRY_TO_NUMBER(ADDRESSID) IS NULL;



CREATE OR REPLACE TASK STAGE_SCH.DELIVERY_TRANSFORM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.DELIVERY_STM_TRANSFORM')
AS
MERGE INTO CLEAN_SCH.DELIVERY AS target
USING (
    SELECT
        TRY_TO_NUMBER(DELIVERYID) AS DELIVERY_ID,
        TRY_TO_NUMBER(ORDERID) AS ORDER_ID_FK,
        TRY_TO_NUMBER(DELIVERYAGENTID) AS DELIVERY_AGENT_ID_FK,
        DELIVERYSTATUS AS DELIVERY_STATUS,
        ESTIMATEDTIME AS ESTIMATED_TIME,
        TRY_TO_NUMBER(ADDRESSID) AS CUSTOMER_ADDRESS_ID_FK,
        TRY_TO_TIMESTAMP_NTZ(DELIVERYDATE) AS DELIVERY_DATE,
        TRY_TO_TIMESTAMP_NTZ(CREATEDDATE) AS CREATED_DATE,
        TRY_TO_TIMESTAMP_NTZ(MODIFIEDDATE) AS MODIFIED_DATE,
        _STG_FILE_NAME,
        _STG_FILE_LOAD_TS,
        _STG_FILE_MD5,
        CURRENT_TIMESTAMP AS _COPY_DATA_TS
    FROM STAGE_SCH.DELIVERY_STM_TRANSFORM
    WHERE TRY_TO_NUMBER(DELIVERYID) IS NOT NULL
) source
ON target.DELIVERY_ID = source.DELIVERY_ID

WHEN MATCHED THEN UPDATE SET
    target.DELIVERY_STATUS = source.DELIVERY_STATUS,
    target.ESTIMATED_TIME = source.ESTIMATED_TIME,
    target.CUSTOMER_ADDRESS_ID_FK = source.CUSTOMER_ADDRESS_ID_FK,
    target.DELIVERY_DATE = source.DELIVERY_DATE,
    target.MODIFIED_DATE = source.MODIFIED_DATE,
    target._STG_FILE_NAME = source._STG_FILE_NAME,
    target._STG_FILE_LOAD_TS = source._STG_FILE_LOAD_TS,
    target._STG_FILE_MD5 = source._STG_FILE_MD5,
    target._COPY_DATA_TS = source._COPY_DATA_TS

WHEN NOT MATCHED THEN INSERT (
    DELIVERY_ID, ORDER_ID_FK, DELIVERY_AGENT_ID_FK,
    DELIVERY_STATUS, ESTIMATED_TIME, CUSTOMER_ADDRESS_ID_FK,
    DELIVERY_DATE, CREATED_DATE, MODIFIED_DATE,
    _STG_FILE_NAME, _STG_FILE_LOAD_TS, _STG_FILE_MD5, _COPY_DATA_TS
)
VALUES (
    source.DELIVERY_ID, source.ORDER_ID_FK, source.DELIVERY_AGENT_ID_FK,
    source.DELIVERY_STATUS, source.ESTIMATED_TIME, source.CUSTOMER_ADDRESS_ID_FK,
    source.DELIVERY_DATE, source.CREATED_DATE, source.MODIFIED_DATE,
    source._STG_FILE_NAME, source._STG_FILE_LOAD_TS,
    source._STG_FILE_MD5, source._COPY_DATA_TS
);

CREATE OR REPLACE TABLE CONSUMPTION_SCH.DELIVERY_DIM (
    DELIVERY_HK NUMBER PRIMARY KEY,
    DELIVERY_ID NUMBER,
    ORDER_ID_FK NUMBER,
    DELIVERY_AGENT_ID_FK NUMBER,
    CUSTOMER_ADDRESS_ID_FK NUMBER,
    DELIVERY_STATUS STRING,
    ESTIMATED_TIME STRING,
    DELIVERY_DATE TIMESTAMP_NTZ,
    EFF_START_DATE TIMESTAMP_NTZ,
    EFF_END_DATE TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN
)
COMMENT = 'SCD2 dimension table for Delivery entity';


CREATE OR REPLACE TASK CLEAN_SCH.DELIVERY_DIM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('CLEAN_SCH.DELIVERY_STM')
AS
MERGE INTO CONSUMPTION_SCH.DELIVERY_DIM AS target
USING CLEAN_SCH.DELIVERY_STM AS source
ON target.DELIVERY_ID = source.DELIVERY_ID
   AND target.IS_CURRENT = TRUE
WHEN MATCHED
 AND source.METADATA$ACTION = 'DELETE'
 AND source.METADATA$ISUPDATE = 'TRUE'
THEN UPDATE SET
    target.EFF_END_DATE = CURRENT_TIMESTAMP(),
    target.IS_CURRENT = FALSE
WHEN NOT MATCHED
 AND source.METADATA$ACTION = 'INSERT'
 AND source.METADATA$ISUPDATE = 'TRUE'
THEN INSERT (
    DELIVERY_HK,
    DELIVERY_ID,
    ORDER_ID_FK,
    DELIVERY_AGENT_ID_FK,
    CUSTOMER_ADDRESS_ID_FK,
    DELIVERY_STATUS,
    ESTIMATED_TIME,
    DELIVERY_DATE,
    EFF_START_DATE,
    EFF_END_DATE,
    IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.DELIVERY_ID,
        source.ORDER_ID_FK,
        source.DELIVERY_AGENT_ID_FK,
        source.CUSTOMER_ADDRESS_ID_FK,
        source.DELIVERY_STATUS,
        source.ESTIMATED_TIME,
        source.DELIVERY_DATE
    ))),
    source.DELIVERY_ID,
    source.ORDER_ID_FK,
    source.DELIVERY_AGENT_ID_FK,
    source.CUSTOMER_ADDRESS_ID_FK,
    source.DELIVERY_STATUS,
    source.ESTIMATED_TIME,
    source.DELIVERY_DATE,
    CURRENT_TIMESTAMP(),
    NULL,
    TRUE
)
WHEN NOT MATCHED
 AND source.METADATA$ACTION = 'INSERT'
 AND source.METADATA$ISUPDATE = 'FALSE'
THEN INSERT (
    DELIVERY_HK,
    DELIVERY_ID,
    ORDER_ID_FK,
    DELIVERY_AGENT_ID_FK,
    CUSTOMER_ADDRESS_ID_FK,
    DELIVERY_STATUS,
    ESTIMATED_TIME,
    DELIVERY_DATE,
    EFF_START_DATE,
    EFF_END_DATE,
    IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.DELIVERY_ID,
        source.ORDER_ID_FK,
        source.DELIVERY_AGENT_ID_FK,
        source.CUSTOMER_ADDRESS_ID_FK,
        source.DELIVERY_STATUS,
        source.ESTIMATED_TIME,
        source.DELIVERY_DATE
    ))),
    source.DELIVERY_ID,
    source.ORDER_ID_FK,
    source.DELIVERY_AGENT_ID_FK,
    source.CUSTOMER_ADDRESS_ID_FK,
    source.DELIVERY_STATUS,
    source.ESTIMATED_TIME,
    source.DELIVERY_DATE,
    CURRENT_TIMESTAMP(),
    NULL,
    TRUE
);


ALTER TASK STAGE_SCH.DELIVERY_DQ_TASK RESUME;
ALTER TASK STAGE_SCH.DELIVERY_TRANSFORM_TASK RESUME;
ALTER TASK CLEAN_SCH.DELIVERY_DIM_TASK RESUME;

ALTER PIPE STAGE_SCH.DELIVERY_PIPE REFRESH;



