USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;



CREATE OR REPLACE TABLE STAGE_SCH.DELIVERYAGENT (
    DELIVERYAGENTID TEXT,
    NAME TEXT,
    PHONE TEXT,
    VEHICLETYPE TEXT,
    LOCATIONID TEXT,
    STATUS TEXT,
    GENDER TEXT,
    RATING TEXT,
    CREATEDDATE TEXT,
    MODIFIEDDATE TEXT,

    _STG_FILE_NAME TEXT,
    _STG_FILE_LOAD_TS TIMESTAMP,
    _STG_FILE_MD5 TEXT,
    _COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE STREAM STAGE_SCH.DELIVERYAGENT_STM_DQ
ON TABLE STAGE_SCH.DELIVERYAGENT
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM STAGE_SCH.DELIVERYAGENT_STM_TRANSFORM
ON TABLE STAGE_SCH.DELIVERYAGENT
APPEND_ONLY = TRUE;


CREATE OR REPLACE TABLE STAGE_SCH.DELIVERYAGENT_DQ_ERROR (
    DELIVERYAGENTID TEXT,
    NAME TEXT,
    PHONE TEXT,
    LOCATIONID TEXT,
    ERROR_REASON TEXT,
    _STG_FILE_NAME TEXT,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE PIPE STAGE_SCH.DELIVERYAGENT_PIPE
AS
COPY INTO STAGE_SCH.DELIVERYAGENT
FROM (
    SELECT
        t.$1::TEXT,
        t.$2::TEXT,
        t.$3::TEXT,
        t.$4::TEXT,
        t.$5::TEXT,
        t.$6::TEXT,
        t.$7::TEXT,
        t.$8::TEXT,
        t.$9::TEXT,
        t.$10::TEXT,
        METADATA$FILENAME,
        METADATA$FILE_LAST_MODIFIED,
        METADATA$FILE_CONTENT_KEY,
        CURRENT_TIMESTAMP
    FROM @STAGE_SCH.CSV_STG/DELIVERY-AGENT t
)
FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT')
ON_ERROR = 'CONTINUE';



CREATE OR REPLACE TABLE CLEAN_SCH.DELIVERY_AGENT (
    DELIVERY_AGENT_SK NUMBER AUTOINCREMENT PRIMARY KEY,
    DELIVERY_AGENT_ID NUMBER UNIQUE,
    NAME STRING NOT NULL,
    PHONE STRING NOT NULL,
    VEHICLE_TYPE STRING,
    LOCATION_ID_FK NUMBER,
    STATUS STRING,
    GENDER STRING,
    RATING NUMBER(4,2),
    CREATED_DT TIMESTAMP_NTZ,
    MODIFIED_DT TIMESTAMP_NTZ,

    _STG_FILE_NAME STRING,
    _STG_FILE_LOAD_TS TIMESTAMP_NTZ,
    _STG_FILE_MD5 STRING,
    _COPY_DATA_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);



CREATE OR REPLACE STREAM CLEAN_SCH.DELIVERY_AGENT_STM
ON TABLE CLEAN_SCH.DELIVERY_AGENT;


CREATE OR REPLACE TASK STAGE_SCH.DELIVERYAGENT_DQ_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.DELIVERYAGENT_STM_DQ')
AS
INSERT INTO STAGE_SCH.DELIVERYAGENT_DQ_ERROR
SELECT
    DELIVERYAGENTID,
    NAME,
    PHONE,
    LOCATIONID,
    CASE
        WHEN TRY_TO_NUMBER(DELIVERYAGENTID) IS NULL THEN 'INVALID DELIVERYAGENTID'
        WHEN NAME IS NULL THEN 'NAME NULL'
        WHEN PHONE IS NULL THEN 'PHONE NULL'
        WHEN TRY_TO_NUMBER(LOCATIONID) IS NULL THEN 'INVALID LOCATIONID'
    END,
    _STG_FILE_NAME,
    CURRENT_TIMESTAMP
FROM STAGE_SCH.DELIVERYAGENT_STM_DQ
WHERE
    TRY_TO_NUMBER(DELIVERYAGENTID) IS NULL
    OR NAME IS NULL
    OR PHONE IS NULL
    OR TRY_TO_NUMBER(LOCATIONID) IS NULL;



CREATE OR REPLACE TASK STAGE_SCH.DELIVERYAGENT_TRANSFORM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.DELIVERYAGENT_STM_TRANSFORM')
AS
MERGE INTO CLEAN_SCH.DELIVERY_AGENT AS target
USING (
    SELECT
        TRY_TO_NUMBER(DELIVERYAGENTID) AS DELIVERY_AGENT_ID,
        NAME,
        PHONE,
        VEHICLETYPE AS VEHICLE_TYPE,
        TRY_TO_NUMBER(LOCATIONID) AS LOCATION_ID_FK,
        STATUS,
        GENDER,
        TRY_TO_NUMBER(RATING,4,2) AS RATING,
        TRY_TO_TIMESTAMP_NTZ(CREATEDDATE) AS CREATED_DT,
        TRY_TO_TIMESTAMP_NTZ(MODIFIEDDATE) AS MODIFIED_DT,
        _STG_FILE_NAME,
        _STG_FILE_LOAD_TS,
        _STG_FILE_MD5,
        CURRENT_TIMESTAMP AS _COPY_DATA_TS
    FROM STAGE_SCH.DELIVERYAGENT_STM_TRANSFORM
    WHERE TRY_TO_NUMBER(DELIVERYAGENTID) IS NOT NULL
) source
ON target.DELIVERY_AGENT_ID = source.DELIVERY_AGENT_ID

WHEN MATCHED THEN UPDATE SET
    target.NAME = source.NAME,
    target.PHONE = source.PHONE,
    target.VEHICLE_TYPE = source.VEHICLE_TYPE,
    target.LOCATION_ID_FK = source.LOCATION_ID_FK,
    target.STATUS = source.STATUS,
    target.GENDER = source.GENDER,
    target.RATING = source.RATING,
    target.MODIFIED_DT = source.MODIFIED_DT,
    target._STG_FILE_NAME = source._STG_FILE_NAME,
    target._STG_FILE_LOAD_TS = source._STG_FILE_LOAD_TS,
    target._STG_FILE_MD5 = source._STG_FILE_MD5,
    target._COPY_DATA_TS = source._COPY_DATA_TS

WHEN NOT MATCHED THEN INSERT (
    DELIVERY_AGENT_ID, NAME, PHONE, VEHICLE_TYPE,
    LOCATION_ID_FK, STATUS, GENDER, RATING,
    CREATED_DT, MODIFIED_DT,
    _STG_FILE_NAME, _STG_FILE_LOAD_TS, _STG_FILE_MD5, _COPY_DATA_TS
)
VALUES (
    source.DELIVERY_AGENT_ID, source.NAME, source.PHONE,
    source.VEHICLE_TYPE, source.LOCATION_ID_FK,
    source.STATUS, source.GENDER, source.RATING,
    source.CREATED_DT, source.MODIFIED_DT,
    source._STG_FILE_NAME, source._STG_FILE_LOAD_TS,
    source._STG_FILE_MD5, source._COPY_DATA_TS
);



CREATE OR REPLACE TABLE CONSUMPTION_SCH.DELIVERY_AGENT_DIM (
    DELIVERY_AGENT_HK NUMBER PRIMARY KEY,
    DELIVERY_AGENT_ID NUMBER,
    NAME STRING,
    PHONE STRING,
    VEHICLE_TYPE STRING,
    LOCATION_ID_FK NUMBER,
    STATUS STRING,
    GENDER STRING,
    RATING NUMBER(4,2),
    EFF_START_DATE TIMESTAMP_NTZ,
    EFF_END_DATE TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN
);


CREATE OR REPLACE TASK CLEAN_SCH.DELIVERY_AGENT_DIM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('CLEAN_SCH.DELIVERY_AGENT_STM')
AS
MERGE INTO CONSUMPTION_SCH.DELIVERY_AGENT_DIM AS target
USING CLEAN_SCH.DELIVERY_AGENT_STM AS source
ON target.DELIVERY_AGENT_ID = source.DELIVERY_AGENT_ID
   AND target.IS_CURRENT = TRUE

WHEN MATCHED
 AND source.METADATA$ACTION = 'DELETE'
 AND source.METADATA$ISUPDATE = 'TRUE'
THEN UPDATE SET
    target.EFF_END_DATE = CURRENT_TIMESTAMP(),
    target.IS_CURRENT = FALSE

WHEN NOT MATCHED
 AND source.METADATA$ACTION = 'INSERT'
 AND source.METADATA$ISUPDATE = 'TRUE'
THEN INSERT (
    DELIVERY_AGENT_HK, DELIVERY_AGENT_ID, NAME, PHONE,
    VEHICLE_TYPE, LOCATION_ID_FK, STATUS, GENDER, RATING,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.DELIVERY_AGENT_ID, source.NAME, source.PHONE,
        source.VEHICLE_TYPE, source.LOCATION_ID_FK,
        source.STATUS, source.GENDER, source.RATING
    ))),
    source.DELIVERY_AGENT_ID, source.NAME, source.PHONE,
    source.VEHICLE_TYPE, source.LOCATION_ID_FK,
    source.STATUS, source.GENDER, source.RATING,
    CURRENT_TIMESTAMP(), NULL, TRUE
)

WHEN NOT MATCHED
 AND source.METADATA$ACTION = 'INSERT'
 AND source.METADATA$ISUPDATE = 'FALSE'
THEN INSERT (
    DELIVERY_AGENT_HK, DELIVERY_AGENT_ID, NAME, PHONE,
    VEHICLE_TYPE, LOCATION_ID_FK, STATUS, GENDER, RATING,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.DELIVERY_AGENT_ID, source.NAME, source.PHONE,
        source.VEHICLE_TYPE, source.LOCATION_ID_FK,
        source.STATUS, source.GENDER, source.RATING
    ))),
    source.DELIVERY_AGENT_ID, source.NAME, source.PHONE,
    source.VEHICLE_TYPE, source.LOCATION_ID_FK,
    source.STATUS, source.GENDER, source.RATING,
    CURRENT_TIMESTAMP(), NULL, TRUE
);


ALTER TASK STAGE_SCH.DELIVERYAGENT_DQ_TASK RESUME;
ALTER TASK STAGE_SCH.DELIVERYAGENT_TRANSFORM_TASK RESUME;
ALTER TASK CLEAN_SCH.DELIVERY_AGENT_DIM_TASK RESUME;

ALTER PIPE STAGE_SCH.DELIVERYAGENT_PIPE REFRESH;


