USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;


CREATE OR REPLACE TABLE STAGE_SCH.MENU (
    MENUID TEXT,
    RESTAURANTID TEXT,
    ITEMNAME TEXT,
    DESCRIPTION TEXT,
    PRICE TEXT,
    CATEGORY TEXT,
    AVAILABILITY TEXT,
    ITEMTYPE TEXT,
    CREATEDDATE TEXT,
    MODIFIEDDATE TEXT,

    _STG_FILE_NAME TEXT,
    _STG_FILE_LOAD_TS TIMESTAMP,
    _STG_FILE_MD5 TEXT,
    _COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE STREAM STAGE_SCH.MENU_STM_DQ
ON TABLE STAGE_SCH.MENU
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM STAGE_SCH.MENU_STM_TRANSFORM
ON TABLE STAGE_SCH.MENU
APPEND_ONLY = TRUE;


CREATE OR REPLACE TABLE STAGE_SCH.MENU_DQ_ERROR (
    MENUID TEXT,
    RESTAURANTID TEXT,
    ITEMNAME TEXT,
    PRICE TEXT,
    ERROR_REASON TEXT,
    _STG_FILE_NAME TEXT,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE PIPE STAGE_SCH.MENU_PIPE
AS
COPY INTO STAGE_SCH.MENU
FROM (
    SELECT
        t.$1::TEXT,
        t.$2::TEXT,
        t.$3::TEXT,
        t.$4::TEXT,
        t.$5::TEXT,
        t.$6::TEXT,
        t.$7::TEXT,
        t.$8::TEXT,
        t.$9::TEXT,
        t.$10::TEXT,
        METADATA$FILENAME,
        METADATA$FILE_LAST_MODIFIED,
        METADATA$FILE_CONTENT_KEY,
        CURRENT_TIMESTAMP
    FROM @STAGE_SCH.CSV_STG/MENU t
)
FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT')
ON_ERROR = 'CONTINUE';



CREATE OR REPLACE TABLE CLEAN_SCH.MENU (
    MENU_SK NUMBER AUTOINCREMENT PRIMARY KEY,
    MENU_ID NUMBER UNIQUE,
    RESTAURANT_ID_FK NUMBER,
    ITEM_NAME STRING NOT NULL,
    DESCRIPTION STRING,
    PRICE DECIMAL(10,2),
    CATEGORY STRING,
    AVAILABILITY BOOLEAN,
    ITEM_TYPE STRING,
    CREATED_DT TIMESTAMP_NTZ,
    MODIFIED_DT TIMESTAMP_NTZ,

    _STG_FILE_NAME STRING,
    _STG_FILE_LOAD_TS TIMESTAMP_NTZ,
    _STG_FILE_MD5 STRING,
    _COPY_DATA_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);



CREATE OR REPLACE STREAM CLEAN_SCH.MENU_STM
ON TABLE CLEAN_SCH.MENU;


CREATE OR REPLACE TASK STAGE_SCH.MENU_DQ_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.MENU_STM_DQ')
AS
INSERT INTO STAGE_SCH.MENU_DQ_ERROR
SELECT
    MENUID,
    RESTAURANTID,
    ITEMNAME,
    PRICE,
    CASE
        WHEN TRY_TO_NUMBER(MENUID) IS NULL THEN 'INVALID MENUID'
        WHEN TRY_TO_NUMBER(RESTAURANTID) IS NULL THEN 'INVALID RESTAURANTID'
        WHEN ITEMNAME IS NULL THEN 'ITEMNAME NULL'
        WHEN TRY_TO_NUMBER(PRICE) IS NULL THEN 'INVALID PRICE'
    END,
    _STG_FILE_NAME,
    CURRENT_TIMESTAMP
FROM STAGE_SCH.MENU_STM_DQ
WHERE
    TRY_TO_NUMBER(MENUID) IS NULL
    OR TRY_TO_NUMBER(RESTAURANTID) IS NULL
    OR ITEMNAME IS NULL
    OR TRY_TO_NUMBER(PRICE) IS NULL;



    CREATE OR REPLACE TASK STAGE_SCH.MENU_TRANSFORM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.MENU_STM_TRANSFORM')
AS
MERGE INTO CLEAN_SCH.MENU AS target
USING (
    SELECT
        TRY_TO_NUMBER(MENUID) AS MENU_ID,
        TRY_TO_NUMBER(RESTAURANTID) AS RESTAURANT_ID_FK,
        TRIM(ITEMNAME) AS ITEM_NAME,
        TRIM(DESCRIPTION) AS DESCRIPTION,
        TRY_TO_NUMBER(PRICE,10,2) AS PRICE,
        TRIM(CATEGORY) AS CATEGORY,
        CASE
            WHEN LOWER(AVAILABILITY) IN ('true','y','yes','1') THEN TRUE
            WHEN LOWER(AVAILABILITY) IN ('false','n','no','0') THEN FALSE
            ELSE NULL
        END AS AVAILABILITY,
        TRIM(ITEMTYPE) AS ITEM_TYPE,
        TRY_TO_TIMESTAMP_NTZ(CREATEDDATE) AS CREATED_DT,
        TRY_TO_TIMESTAMP_NTZ(MODIFIEDDATE) AS MODIFIED_DT,
        _STG_FILE_NAME,
        _STG_FILE_LOAD_TS,
        _STG_FILE_MD5,
        CURRENT_TIMESTAMP AS _COPY_DATA_TS
    FROM STAGE_SCH.MENU_STM_TRANSFORM
    WHERE TRY_TO_NUMBER(MENUID) IS NOT NULL
) source
ON target.MENU_ID = source.MENU_ID

WHEN MATCHED THEN UPDATE SET
    target.RESTAURANT_ID_FK = source.RESTAURANT_ID_FK,
    target.ITEM_NAME = source.ITEM_NAME,
    target.DESCRIPTION = source.DESCRIPTION,
    target.PRICE = source.PRICE,
    target.CATEGORY = source.CATEGORY,
    target.AVAILABILITY = source.AVAILABILITY,
    target.ITEM_TYPE = source.ITEM_TYPE,
    target.MODIFIED_DT = source.MODIFIED_DT,
    target._STG_FILE_NAME = source._STG_FILE_NAME,
    target._STG_FILE_LOAD_TS = source._STG_FILE_LOAD_TS,
    target._STG_FILE_MD5 = source._STG_FILE_MD5,
    target._COPY_DATA_TS = source._COPY_DATA_TS

WHEN NOT MATCHED THEN INSERT (
    MENU_ID, RESTAURANT_ID_FK, ITEM_NAME, DESCRIPTION,
    PRICE, CATEGORY, AVAILABILITY, ITEM_TYPE,
    CREATED_DT, MODIFIED_DT,
    _STG_FILE_NAME, _STG_FILE_LOAD_TS, _STG_FILE_MD5, _COPY_DATA_TS
)
VALUES (
    source.MENU_ID, source.RESTAURANT_ID_FK, source.ITEM_NAME, source.DESCRIPTION,
    source.PRICE, source.CATEGORY, source.AVAILABILITY, source.ITEM_TYPE,
    source.CREATED_DT, source.MODIFIED_DT,
    source._STG_FILE_NAME, source._STG_FILE_LOAD_TS, source._STG_FILE_MD5, source._COPY_DATA_TS
);



CREATE OR REPLACE TABLE CONSUMPTION_SCH.MENU_DIM (
    MENU_DIM_HK NUMBER PRIMARY KEY,
    MENU_ID NUMBER,
    RESTAURANT_ID_FK NUMBER,
    ITEM_NAME STRING,
    DESCRIPTION STRING,
    PRICE DECIMAL(10,2),
    CATEGORY STRING,
    AVAILABILITY BOOLEAN,
    ITEM_TYPE STRING,
    EFF_START_DATE TIMESTAMP_NTZ,
    EFF_END_DATE TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN
);


CREATE OR REPLACE TASK CLEAN_SCH.MENU_DIM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('CLEAN_SCH.MENU_STM')
AS
MERGE INTO CONSUMPTION_SCH.MENU_DIM AS target
USING CLEAN_SCH.MENU_STM AS source
ON target.MENU_ID = source.MENU_ID
   AND target.IS_CURRENT = TRUE

WHEN MATCHED
 AND source.METADATA$ACTION = 'DELETE'
 AND source.METADATA$ISUPDATE = 'TRUE'
THEN UPDATE SET
    target.EFF_END_DATE = CURRENT_TIMESTAMP(),
    target.IS_CURRENT = FALSE

WHEN NOT MATCHED
 AND source.METADATA$ACTION = 'INSERT'
 AND source.METADATA$ISUPDATE = 'TRUE'
THEN INSERT (
    MENU_DIM_HK, MENU_ID, RESTAURANT_ID_FK,
    ITEM_NAME, DESCRIPTION, PRICE, CATEGORY,
    AVAILABILITY, ITEM_TYPE,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.MENU_ID, source.RESTAURANT_ID_FK,
        source.ITEM_NAME, source.DESCRIPTION,
        source.PRICE, source.CATEGORY,
        source.AVAILABILITY, source.ITEM_TYPE
    ))),
    source.MENU_ID, source.RESTAURANT_ID_FK,
    source.ITEM_NAME, source.DESCRIPTION, source.PRICE,
    source.CATEGORY, source.AVAILABILITY, source.ITEM_TYPE,
    CURRENT_TIMESTAMP(), NULL, TRUE
)

WHEN NOT MATCHED
 AND source.METADATA$ACTION = 'INSERT'
 AND source.METADATA$ISUPDATE = 'FALSE'
THEN INSERT (
    MENU_DIM_HK, MENU_ID, RESTAURANT_ID_FK,
    ITEM_NAME, DESCRIPTION, PRICE, CATEGORY,
    AVAILABILITY, ITEM_TYPE,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.MENU_ID, source.RESTAURANT_ID_FK,
        source.ITEM_NAME, source.DESCRIPTION,
        source.PRICE, source.CATEGORY,
        source.AVAILABILITY, source.ITEM_TYPE
    ))),
    source.MENU_ID, source.RESTAURANT_ID_FK,
    source.ITEM_NAME, source.DESCRIPTION, source.PRICE,
    source.CATEGORY, source.AVAILABILITY, source.ITEM_TYPE,
    CURRENT_TIMESTAMP(), NULL, TRUE
);



ALTER TASK STAGE_SCH.MENU_DQ_TASK RESUME;
ALTER TASK STAGE_SCH.MENU_TRANSFORM_TASK RESUME;
ALTER TASK CLEAN_SCH.MENU_DIM_TASK RESUME;

ALTER PIPE STAGE_SCH.MENU_PIPE REFRESH;

