USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;



CREATE OR REPLACE TABLE STAGE_SCH.ORDERS (
    ORDERID TEXT,
    CUSTOMERID TEXT,
    RESTAURANTID TEXT,
    ORDERDATE TEXT,
    TOTALAMOUNT TEXT,
    STATUS TEXT,
    PAYMENTMETHOD TEXT,
    CREATEDDATE TEXT,
    MODIFIEDDATE TEXT,

    _STG_FILE_NAME TEXT,
    _STG_FILE_LOAD_TS TIMESTAMP,
    _STG_FILE_MD5 TEXT,
    _COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE STREAM STAGE_SCH.ORDERS_STM_DQ
ON TABLE STAGE_SCH.ORDERS
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM STAGE_SCH.ORDERS_STM_TRANSFORM
ON TABLE STAGE_SCH.ORDERS
APPEND_ONLY = TRUE;


CREATE OR REPLACE TABLE STAGE_SCH.ORDERS_DQ_ERROR (
    ORDERID TEXT,
    CUSTOMERID TEXT,
    RESTAURANTID TEXT,
    TOTALAMOUNT TEXT,
    ERROR_REASON TEXT,
    _STG_FILE_NAME TEXT,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE PIPE STAGE_SCH.ORDERS_PIPE
AS
COPY INTO STAGE_SCH.ORDERS
FROM (
    SELECT
        t.$1::TEXT,
        t.$2::TEXT,
        t.$3::TEXT,
        t.$4::TEXT,
        t.$5::TEXT,
        t.$6::TEXT,
        t.$7::TEXT,
        t.$8::TEXT,
        t.$9::TEXT,
        METADATA$FILENAME,
        METADATA$FILE_LAST_MODIFIED,
        METADATA$FILE_CONTENT_KEY,
        CURRENT_TIMESTAMP
    FROM @STAGE_SCH.CSV_STG/ORDERS t
)
FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT')
ON_ERROR = 'CONTINUE';


CREATE OR REPLACE TABLE CLEAN_SCH.ORDERS (
    ORDER_SK NUMBER AUTOINCREMENT PRIMARY KEY,
    ORDER_ID NUMBER UNIQUE,
    CUSTOMER_ID_FK NUMBER,
    RESTAURANT_ID_FK NUMBER,
    ORDER_DATE TIMESTAMP_NTZ,
    TOTAL_AMOUNT DECIMAL(10,2),
    STATUS STRING,
    PAYMENT_METHOD STRING,
    CREATED_DT TIMESTAMP_TZ,
    MODIFIED_DT TIMESTAMP_TZ,

    _STG_FILE_NAME STRING,
    _STG_FILE_LOAD_TS TIMESTAMP_NTZ,
    _STG_FILE_MD5 STRING,
    _COPY_DATA_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE STREAM CLEAN_SCH.ORDERS_STM
ON TABLE CLEAN_SCH.ORDERS;


CREATE OR REPLACE TASK STAGE_SCH.ORDERS_DQ_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.ORDERS_STM_DQ')
AS
INSERT INTO STAGE_SCH.ORDERS_DQ_ERROR
SELECT
    ORDERID,
    CUSTOMERID,
    RESTAURANTID,
    TOTALAMOUNT,
    CASE
        WHEN TRY_TO_NUMBER(ORDERID) IS NULL THEN 'INVALID ORDERID'
        WHEN TRY_TO_NUMBER(CUSTOMERID) IS NULL THEN 'INVALID CUSTOMERID'
        WHEN TRY_TO_NUMBER(RESTAURANTID) IS NULL THEN 'INVALID RESTAURANTID'
        WHEN TRY_TO_DECIMAL(TOTALAMOUNT) IS NULL THEN 'INVALID TOTALAMOUNT'
    END,
    _STG_FILE_NAME,
    CURRENT_TIMESTAMP
FROM STAGE_SCH.ORDERS_STM_DQ
WHERE
    TRY_TO_NUMBER(ORDERID) IS NULL
    OR TRY_TO_NUMBER(CUSTOMERID) IS NULL
    OR TRY_TO_NUMBER(RESTAURANTID) IS NULL
    OR TRY_TO_DECIMAL(TOTALAMOUNT) IS NULL;



CREATE OR REPLACE TASK STAGE_SCH.ORDERS_TRANSFORM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.ORDERS_STM_TRANSFORM')
AS
MERGE INTO CLEAN_SCH.ORDERS AS target
USING (
    SELECT
        TRY_TO_NUMBER(ORDERID) AS ORDER_ID,
        TRY_TO_NUMBER(CUSTOMERID) AS CUSTOMER_ID_FK,
        TRY_TO_NUMBER(RESTAURANTID) AS RESTAURANT_ID_FK,
        TRY_TO_TIMESTAMP_NTZ(ORDERDATE) AS ORDER_DATE,
        TRY_TO_DECIMAL(TOTALAMOUNT,10,2) AS TOTAL_AMOUNT,
        STATUS,
        PAYMENTMETHOD AS PAYMENT_METHOD,
        TRY_TO_TIMESTAMP_TZ(CREATEDDATE) AS CREATED_DT,
        TRY_TO_TIMESTAMP_TZ(MODIFIEDDATE) AS MODIFIED_DT,
        _STG_FILE_NAME,
        _STG_FILE_LOAD_TS,
        _STG_FILE_MD5,
        CURRENT_TIMESTAMP AS _COPY_DATA_TS
    FROM STAGE_SCH.ORDERS_STM_TRANSFORM
    WHERE TRY_TO_NUMBER(ORDERID) IS NOT NULL
) source
ON target.ORDER_ID = source.ORDER_ID

WHEN MATCHED THEN UPDATE SET
    target.TOTAL_AMOUNT = source.TOTAL_AMOUNT,
    target.STATUS = source.STATUS,
    target.PAYMENT_METHOD = source.PAYMENT_METHOD,
    target.MODIFIED_DT = source.MODIFIED_DT,
    target._STG_FILE_NAME = source._STG_FILE_NAME,
    target._STG_FILE_LOAD_TS = source._STG_FILE_LOAD_TS,
    target._STG_FILE_MD5 = source._STG_FILE_MD5,
    target._COPY_DATA_TS = source._COPY_DATA_TS

WHEN NOT MATCHED THEN INSERT (
    ORDER_ID, CUSTOMER_ID_FK, RESTAURANT_ID_FK,
    ORDER_DATE, TOTAL_AMOUNT, STATUS, PAYMENT_METHOD,
    CREATED_DT, MODIFIED_DT,
    _STG_FILE_NAME, _STG_FILE_LOAD_TS, _STG_FILE_MD5, _COPY_DATA_TS
)
VALUES (
    source.ORDER_ID, source.CUSTOMER_ID_FK, source.RESTAURANT_ID_FK,
    source.ORDER_DATE, source.TOTAL_AMOUNT, source.STATUS, source.PAYMENT_METHOD,
    source.CREATED_DT, source.MODIFIED_DT,
    source._STG_FILE_NAME, source._STG_FILE_LOAD_TS,
    source._STG_FILE_MD5, source._COPY_DATA_TS
);


CREATE OR REPLACE TABLE CONSUMPTION_SCH.ORDERS_DIM (
    ORDER_HK NUMBER PRIMARY KEY,
    ORDER_ID NUMBER,
    CUSTOMER_ID_FK NUMBER,
    RESTAURANT_ID_FK NUMBER,
    ORDER_DATE TIMESTAMP_NTZ,
    TOTAL_AMOUNT DECIMAL(10,2),
    STATUS STRING,
    PAYMENT_METHOD STRING,
    EFF_START_DATE TIMESTAMP_NTZ,
    EFF_END_DATE TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN
);


CREATE OR REPLACE TASK CLEAN_SCH.ORDERS_DIM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('CLEAN_SCH.ORDERS_STM')
AS
MERGE INTO CONSUMPTION_SCH.ORDERS_DIM AS target
USING CLEAN_SCH.ORDERS_STM AS source
ON target.ORDER_ID = source.ORDER_ID
   AND target.IS_CURRENT = TRUE

WHEN MATCHED
 AND source.METADATA$ACTION = 'DELETE'
 AND source.METADATA$ISUPDATE = 'TRUE'
THEN UPDATE SET
    target.EFF_END_DATE = CURRENT_TIMESTAMP(),
    target.IS_CURRENT = FALSE

WHEN NOT MATCHED
 AND source.METADATA$ACTION = 'INSERT'
 AND source.METADATA$ISUPDATE = 'TRUE'
THEN INSERT (
    ORDER_HK, ORDER_ID, CUSTOMER_ID_FK, RESTAURANT_ID_FK,
    ORDER_DATE, TOTAL_AMOUNT, STATUS, PAYMENT_METHOD,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.ORDER_ID,
        source.CUSTOMER_ID_FK,
        source.RESTAURANT_ID_FK,
        source.ORDER_DATE,
        source.TOTAL_AMOUNT,
        source.STATUS,
        source.PAYMENT_METHOD
    ))),
    source.ORDER_ID, source.CUSTOMER_ID_FK, source.RESTAURANT_ID_FK,
    source.ORDER_DATE, source.TOTAL_AMOUNT, source.STATUS, source.PAYMENT_METHOD,
    CURRENT_TIMESTAMP(), NULL, TRUE
)

WHEN NOT MATCHED
 AND source.METADATA$ACTION = 'INSERT'
 AND source.METADATA$ISUPDATE = 'FALSE'
THEN INSERT (
    ORDER_HK, ORDER_ID, CUSTOMER_ID_FK, RESTAURANT_ID_FK,
    ORDER_DATE, TOTAL_AMOUNT, STATUS, PAYMENT_METHOD,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.ORDER_ID,
        source.CUSTOMER_ID_FK,
        source.RESTAURANT_ID_FK,
        source.ORDER_DATE,
        source.TOTAL_AMOUNT,
        source.STATUS,
        source.PAYMENT_METHOD
    ))),
    source.ORDER_ID, source.CUSTOMER_ID_FK, source.RESTAURANT_ID_FK,
    source.ORDER_DATE, source.TOTAL_AMOUNT, source.STATUS, source.PAYMENT_METHOD,
    CURRENT_TIMESTAMP(), NULL, TRUE
);

ALTER TASK STAGE_SCH.ORDERS_DQ_TASK RESUME;
ALTER TASK STAGE_SCH.ORDERS_TRANSFORM_TASK RESUME;
ALTER TASK CLEAN_SCH.ORDERS_DIM_TASK RESUME;

ALTER PIPE STAGE_SCH.ORDERS_PIPE REFRESH;

SELECT * FROM CONSUMPTION_SCH.ORDERS_DIM;


