USE ROLE SYSADMIN;
USE DATABASE SANDBOX;
USE WAREHOUSE COMPUTE_WH;



CREATE OR REPLACE TABLE STAGE_SCH.ORDERITEM (
    ORDERITEMID TEXT,
    ORDERID TEXT,
    MENUID TEXT,
    QUANTITY TEXT,
    PRICE TEXT,
    SUBTOTAL TEXT,
    CREATEDDATE TEXT,
    MODIFIEDDATE TEXT,

    _STG_FILE_NAME TEXT,
    _STG_FILE_LOAD_TS TIMESTAMP,
    _STG_FILE_MD5 TEXT,
    _COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE STREAM STAGE_SCH.ORDERITEM_STM_DQ
ON TABLE STAGE_SCH.ORDERITEM
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM STAGE_SCH.ORDERITEM_STM_TRANSFORM
ON TABLE STAGE_SCH.ORDERITEM
APPEND_ONLY = TRUE;


CREATE OR REPLACE TABLE STAGE_SCH.ORDERITEM_DQ_ERROR (
    ORDERITEMID TEXT,
    ORDERID TEXT,
    MENUID TEXT,
    QUANTITY TEXT,
    PRICE TEXT,
    ERROR_REASON TEXT,
    _STG_FILE_NAME TEXT,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE PIPE STAGE_SCH.ORDERITEM_PIPE
AS
COPY INTO STAGE_SCH.ORDERITEM
FROM (
    SELECT
        t.$1::TEXT,
        t.$2::TEXT,
        t.$3::TEXT,
        t.$4::TEXT,
        t.$5::TEXT,
        t.$6::TEXT,
        t.$7::TEXT,
        t.$8::TEXT,
        METADATA$FILENAME,
        METADATA$FILE_LAST_MODIFIED,
        METADATA$FILE_CONTENT_KEY,
        CURRENT_TIMESTAMP
    FROM @STAGE_SCH.CSV_STG/ORDER-ITEMS t
)
FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT')
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE CLEAN_SCH.ORDER_ITEM (
    ORDER_ITEM_SK NUMBER AUTOINCREMENT PRIMARY KEY,
    ORDER_ITEM_ID NUMBER UNIQUE,
    ORDER_ID_FK NUMBER,
    MENU_ID_FK NUMBER,
    QUANTITY NUMBER,
    PRICE DECIMAL(10,2),
    SUBTOTAL DECIMAL(10,2),
    CREATED_DT TIMESTAMP_NTZ,
    MODIFIED_DT TIMESTAMP_NTZ,

    _STG_FILE_NAME STRING,
    _STG_FILE_LOAD_TS TIMESTAMP_NTZ,
    _STG_FILE_MD5 STRING,
    _COPY_DATA_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE STREAM CLEAN_SCH.ORDER_ITEM_STM
ON TABLE CLEAN_SCH.ORDER_ITEM;


CREATE OR REPLACE TASK STAGE_SCH.ORDERITEM_DQ_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.ORDERITEM_STM_DQ')
AS
INSERT INTO STAGE_SCH.ORDERITEM_DQ_ERROR
SELECT
    ORDERITEMID,
    ORDERID,
    MENUID,
    QUANTITY,
    PRICE,
    CASE
        WHEN TRY_TO_NUMBER(ORDERITEMID) IS NULL THEN 'INVALID ORDERITEMID'
        WHEN TRY_TO_NUMBER(ORDERID) IS NULL THEN 'INVALID ORDERID'
        WHEN TRY_TO_NUMBER(MENUID) IS NULL THEN 'INVALID MENUID'
        WHEN TRY_TO_NUMBER(QUANTITY) IS NULL THEN 'INVALID QUANTITY'
        WHEN TRY_TO_DECIMAL(PRICE) IS NULL THEN 'INVALID PRICE'
    END,
    _STG_FILE_NAME,
    CURRENT_TIMESTAMP
FROM STAGE_SCH.ORDERITEM_STM_DQ
WHERE
    TRY_TO_NUMBER(ORDERITEMID) IS NULL
    OR TRY_TO_NUMBER(ORDERID) IS NULL
    OR TRY_TO_NUMBER(MENUID) IS NULL
    OR TRY_TO_NUMBER(QUANTITY) IS NULL
    OR TRY_TO_DECIMAL(PRICE) IS NULL;


CREATE OR REPLACE TASK STAGE_SCH.ORDERITEM_TRANSFORM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.ORDERITEM_STM_TRANSFORM')
AS
MERGE INTO CLEAN_SCH.ORDER_ITEM AS target
USING (
    SELECT
        TRY_TO_NUMBER(ORDERITEMID) AS ORDER_ITEM_ID,
        TRY_TO_NUMBER(ORDERID) AS ORDER_ID_FK,
        TRY_TO_NUMBER(MENUID) AS MENU_ID_FK,
        TRY_TO_NUMBER(QUANTITY) AS QUANTITY,
        TRY_TO_DECIMAL(PRICE,10,2) AS PRICE,
        TRY_TO_DECIMAL(SUBTOTAL,10,2) AS SUBTOTAL,
        TRY_TO_TIMESTAMP_NTZ(CREATEDDATE) AS CREATED_DT,
        TRY_TO_TIMESTAMP_NTZ(MODIFIEDDATE) AS MODIFIED_DT,
        _STG_FILE_NAME,
        _STG_FILE_LOAD_TS,
        _STG_FILE_MD5,
        CURRENT_TIMESTAMP AS _COPY_DATA_TS
    FROM STAGE_SCH.ORDERITEM_STM_TRANSFORM
    WHERE TRY_TO_NUMBER(ORDERITEMID) IS NOT NULL
) source
ON target.ORDER_ITEM_ID = source.ORDER_ITEM_ID

WHEN MATCHED THEN UPDATE SET
    target.QUANTITY = source.QUANTITY,
    target.PRICE = source.PRICE,
    target.SUBTOTAL = source.SUBTOTAL,
    target.MODIFIED_DT = source.MODIFIED_DT,
    target._STG_FILE_NAME = source._STG_FILE_NAME,
    target._STG_FILE_LOAD_TS = source._STG_FILE_LOAD_TS,
    target._STG_FILE_MD5 = source._STG_FILE_MD5,
    target._COPY_DATA_TS = source._COPY_DATA_TS

WHEN NOT MATCHED THEN INSERT (
    ORDER_ITEM_ID, ORDER_ID_FK, MENU_ID_FK,
    QUANTITY, PRICE, SUBTOTAL,
    CREATED_DT, MODIFIED_DT,
    _STG_FILE_NAME, _STG_FILE_LOAD_TS, _STG_FILE_MD5, _COPY_DATA_TS
)
VALUES (
    source.ORDER_ITEM_ID, source.ORDER_ID_FK, source.MENU_ID_FK,
    source.QUANTITY, source.PRICE, source.SUBTOTAL,
    source.CREATED_DT, source.MODIFIED_DT,
    source._STG_FILE_NAME, source._STG_FILE_LOAD_TS,
    source._STG_FILE_MD5, source._COPY_DATA_TS
);


CREATE OR REPLACE TABLE CONSUMPTION_SCH.ORDER_ITEM_DIM (
    ORDER_ITEM_HK NUMBER PRIMARY KEY,
    ORDER_ITEM_ID NUMBER,
    ORDER_ID_FK NUMBER,
    MENU_ID_FK NUMBER,
    QUANTITY NUMBER,
    PRICE DECIMAL(10,2),
    SUBTOTAL DECIMAL(10,2),
    EFF_START_DATE TIMESTAMP_NTZ,
    EFF_END_DATE TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN
);


CREATE OR REPLACE TASK CLEAN_SCH.ORDER_ITEM_DIM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('CLEAN_SCH.ORDER_ITEM_STM')
AS
MERGE INTO CONSUMPTION_SCH.ORDER_ITEM_DIM AS target
USING CLEAN_SCH.ORDER_ITEM_STM AS source
ON target.ORDER_ITEM_ID = source.ORDER_ITEM_ID
   AND target.IS_CURRENT = TRUE

WHEN MATCHED
 AND source.METADATA$ACTION = 'DELETE'
 AND source.METADATA$ISUPDATE = 'TRUE'
THEN UPDATE SET
    target.EFF_END_DATE = CURRENT_TIMESTAMP(),
    target.IS_CURRENT = FALSE

WHEN NOT MATCHED
 AND source.METADATA$ACTION = 'INSERT'
 AND source.METADATA$ISUPDATE = 'TRUE'
THEN INSERT (
    ORDER_ITEM_HK, ORDER_ITEM_ID, ORDER_ID_FK, MENU_ID_FK,
    QUANTITY, PRICE, SUBTOTAL,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.ORDER_ITEM_ID,
        source.ORDER_ID_FK,
        source.MENU_ID_FK,
        source.QUANTITY,
        source.PRICE,
        source.SUBTOTAL
    ))),
    source.ORDER_ITEM_ID, source.ORDER_ID_FK, source.MENU_ID_FK,
    source.QUANTITY, source.PRICE, source.SUBTOTAL,
    CURRENT_TIMESTAMP(), NULL, TRUE
)

WHEN NOT MATCHED
 AND source.METADATA$ACTION = 'INSERT'
 AND source.METADATA$ISUPDATE = 'FALSE'
THEN INSERT (
    ORDER_ITEM_HK, ORDER_ITEM_ID, ORDER_ID_FK, MENU_ID_FK,
    QUANTITY, PRICE, SUBTOTAL,
    EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.ORDER_ITEM_ID,
        source.ORDER_ID_FK,
        source.MENU_ID_FK,
        source.QUANTITY,
        source.PRICE,
        source.SUBTOTAL
    ))),
    source.ORDER_ITEM_ID, source.ORDER_ID_FK, source.MENU_ID_FK,
    source.QUANTITY, source.PRICE, source.SUBTOTAL,
    CURRENT_TIMESTAMP(), NULL, TRUE
);


ALTER TASK STAGE_SCH.ORDERITEM_DQ_TASK RESUME;
ALTER TASK STAGE_SCH.ORDERITEM_TRANSFORM_TASK RESUME;
ALTER TASK CLEAN_SCH.ORDER_ITEM_DIM_TASK RESUME;

ALTER PIPE STAGE_SCH.ORDERITEM_PIPE REFRESH;

