USE ROLE SYSADMIN;
USE DATABASE SANDBOX;


CREATE OR REPLACE TABLE STAGE_SCH.RESTAURANT (
    RESTAURANTID TEXT,
    NAME TEXT,
    CUISINETYPE TEXT,
    PRICING_FOR_2 TEXT,
    RESTAURANT_PHONE TEXT 
        WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),
    OPERATINGHOURS TEXT,
    LOCATIONID TEXT,
    ACTIVEFLAG TEXT,
    OPENSTATUS TEXT,
    LOCALITY TEXT,
    RESTAURANT_ADDRESS TEXT,
    LATITUDE TEXT,
    LONGITUDE TEXT,
    CREATEDDATE TEXT,
    MODIFIEDDATE TEXT,

    _STG_FILE_NAME TEXT,
    _STG_FILE_LOAD_TS TIMESTAMP,
    _STG_FILE_MD5 TEXT,
    _COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE STREAM STAGE_SCH.RESTAURANT_STM_DQ
ON TABLE STAGE_SCH.RESTAURANT
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM STAGE_SCH.RESTAURANT_STM_TRANSFORM
ON TABLE STAGE_SCH.RESTAURANT
APPEND_ONLY = TRUE;

CREATE OR REPLACE TABLE STAGE_SCH.RESTAURANT_DQ_ERROR (
    RESTAURANTID TEXT,
    NAME TEXT,
    LOCATIONID TEXT,
    ERROR_REASON TEXT,
    _STG_FILE_NAME TEXT,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE PIPE STAGE_SCH.RESTAURANT_PIPE
AS
COPY INTO STAGE_SCH.RESTAURANT
FROM (
    SELECT
        t.$1::TEXT,
        t.$2::TEXT,
        t.$3::TEXT,
        t.$4::TEXT,
        t.$5::TEXT,
        t.$6::TEXT,
        t.$7::TEXT,
        t.$8::TEXT,
        t.$9::TEXT,
        t.$10::TEXT,
        t.$11::TEXT,
        t.$12::TEXT,
        t.$13::TEXT,
        t.$14::TEXT,
        t.$15::TEXT,
        METADATA$FILENAME,
        METADATA$FILE_LAST_MODIFIED,
        METADATA$FILE_CONTENT_KEY,
        CURRENT_TIMESTAMP
    FROM @STAGE_SCH.CSV_STG/RESTAURANT t
)
FILE_FORMAT = (FORMAT_NAME = 'STAGE_SCH.CSV_FILE_FORMAT')
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE TABLE CLEAN_SCH.RESTAURANT (
    RESTAURANT_SK NUMBER AUTOINCREMENT PRIMARY KEY,
    RESTAURANT_ID NUMBER UNIQUE,
    NAME STRING(100),
    CUISINE_TYPE STRING,
    PRICING_FOR_TWO NUMBER(10,2),
    RESTAURANT_PHONE STRING(15) 
        WITH TAG (COMMON.PII_POLICY_TAG = 'SENSITIVE'),
    OPERATING_HOURS STRING(100),
    LOCATION_ID_FK NUMBER,
    ACTIVE_FLAG STRING(10),
    OPEN_STATUS STRING(10),
    LOCALITY STRING(100),
    RESTAURANT_ADDRESS STRING,
    LATITUDE NUMBER(9,6),
    LONGITUDE NUMBER(9,6),
    CREATED_DT TIMESTAMP_TZ,
    MODIFIED_DT TIMESTAMP_TZ,

    _STG_FILE_NAME STRING,
    _STG_FILE_LOAD_TS TIMESTAMP,
    _STG_FILE_MD5 STRING,
    _COPY_DATA_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE OR REPLACE STREAM CLEAN_SCH.RESTAURANT_STM
ON TABLE CLEAN_SCH.RESTAURANT;



CREATE OR REPLACE TASK STAGE_SCH.RESTAURANT_DQ_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.RESTAURANT_STM_DQ')
AS
INSERT INTO STAGE_SCH.RESTAURANT_DQ_ERROR
SELECT
    RESTAURANTID,
    NAME,
    LOCATIONID,
    CASE
        WHEN TRY_TO_NUMBER(RESTAURANTID) IS NULL THEN 'INVALID RESTAURANTID'
        WHEN NAME IS NULL THEN 'NAME NULL'
        WHEN TRY_TO_NUMBER(LOCATIONID) IS NULL THEN 'INVALID LOCATIONID'
    END,
    _STG_FILE_NAME,
    CURRENT_TIMESTAMP
FROM STAGE_SCH.RESTAURANT_STM_DQ
WHERE
    TRY_TO_NUMBER(RESTAURANTID) IS NULL
    OR NAME IS NULL
    OR TRY_TO_NUMBER(LOCATIONID) IS NULL;


    CREATE OR REPLACE TASK STAGE_SCH.RESTAURANT_TRANSFORM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('STAGE_SCH.RESTAURANT_STM_TRANSFORM')
AS
MERGE INTO CLEAN_SCH.RESTAURANT AS target
USING (
    SELECT
        TRY_TO_NUMBER(RESTAURANTID) AS RESTAURANT_ID,
        NAME,
        CUISINETYPE AS CUISINE_TYPE,
        TRY_TO_NUMBER(PRICING_FOR_2,10,2) AS PRICING_FOR_TWO,
        RESTAURANT_PHONE,
        OPERATINGHOURS AS OPERATING_HOURS,
        TRY_TO_NUMBER(LOCATIONID) AS LOCATION_ID_FK,
        ACTIVEFLAG,
        OPENSTATUS,
        LOCALITY,
        RESTAURANT_ADDRESS,
        TRY_TO_NUMBER(LATITUDE,9,6) AS LATITUDE,
        TRY_TO_NUMBER(LONGITUDE,9,6) AS LONGITUDE,
        TRY_TO_TIMESTAMP_TZ(CREATEDDATE,'YYYY-MM-DD HH24:MI:SS.FF9') AS CREATED_DT,
        TRY_TO_TIMESTAMP_TZ(MODIFIEDDATE,'YYYY-MM-DD HH24:MI:SS.FF9') AS MODIFIED_DT,
        _STG_FILE_NAME,
        _STG_FILE_LOAD_TS,
        _STG_FILE_MD5,
        CURRENT_TIMESTAMP AS _COPY_DATA_TS
    FROM STAGE_SCH.RESTAURANT_STM_TRANSFORM
    WHERE TRY_TO_NUMBER(RESTAURANTID) IS NOT NULL
) source
ON target.RESTAURANT_ID = source.RESTAURANT_ID

WHEN MATCHED THEN UPDATE SET
    target.NAME = source.NAME,
    target.CUISINE_TYPE = source.CUISINE_TYPE,
    target.PRICING_FOR_TWO = source.PRICING_FOR_TWO,
    target.RESTAURANT_PHONE = source.RESTAURANT_PHONE,
    target.OPERATING_HOURS = source.OPERATING_HOURS,
    target.LOCATION_ID_FK = source.LOCATION_ID_FK,
    target.ACTIVE_FLAG = source.ACTIVEFLAG,
    target.OPEN_STATUS = source.OPENSTATUS,
    target.LOCALITY = source.LOCALITY,
    target.RESTAURANT_ADDRESS = source.RESTAURANT_ADDRESS,
    target.LATITUDE = source.LATITUDE,
    target.LONGITUDE = source.LONGITUDE,
    target.MODIFIED_DT = source.MODIFIED_DT

WHEN NOT MATCHED THEN INSERT (
    RESTAURANT_ID, NAME, CUISINE_TYPE, PRICING_FOR_TWO,
    RESTAURANT_PHONE, OPERATING_HOURS, LOCATION_ID_FK,
    ACTIVE_FLAG, OPEN_STATUS, LOCALITY, RESTAURANT_ADDRESS,
    LATITUDE, LONGITUDE, CREATED_DT, MODIFIED_DT,
    _STG_FILE_NAME, _STG_FILE_LOAD_TS, _STG_FILE_MD5, _COPY_DATA_TS
)
VALUES (
    source.RESTAURANT_ID, source.NAME, source.CUISINE_TYPE, source.PRICING_FOR_TWO,
    source.RESTAURANT_PHONE, source.OPERATING_HOURS, source.LOCATION_ID_FK,
    source.ACTIVEFLAG, source.OPENSTATUS, source.LOCALITY, source.RESTAURANT_ADDRESS,
    source.LATITUDE, source.LONGITUDE, source.CREATED_DT, source.MODIFIED_DT,
    source._STG_FILE_NAME, source._STG_FILE_LOAD_TS, source._STG_FILE_MD5, source._COPY_DATA_TS
);


CREATE OR REPLACE TABLE CONSUMPTION_SCH.RESTAURANT_DIM (
    RESTAURANT_HK NUMBER PRIMARY KEY,
    RESTAURANT_ID NUMBER,
    NAME STRING(100),
    CUISINE_TYPE STRING,
    PRICING_FOR_TWO NUMBER(10,2),
    RESTAURANT_PHONE STRING(15),
    OPERATING_HOURS STRING(100),
    LOCATION_ID_FK NUMBER,
    ACTIVE_FLAG STRING(10),
    OPEN_STATUS STRING(10),
    LOCALITY STRING(100),
    RESTAURANT_ADDRESS STRING,
    LATITUDE NUMBER(9,6),
    LONGITUDE NUMBER(9,6),
    EFF_START_DATE TIMESTAMP_TZ,
    EFF_END_DATE TIMESTAMP_TZ,
    IS_CURRENT BOOLEAN
);



CREATE OR REPLACE TASK CLEAN_SCH.RESTAURANT_DIM_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('CLEAN_SCH.RESTAURANT_STM')
AS
MERGE INTO CONSUMPTION_SCH.RESTAURANT_DIM AS target
USING CLEAN_SCH.RESTAURANT_STM AS source
ON target.RESTAURANT_ID = source.RESTAURANT_ID
   AND target.IS_CURRENT = TRUE

WHEN MATCHED AND source.METADATA$ACTION = 'DELETE'
THEN UPDATE SET
    target.EFF_END_DATE = CURRENT_TIMESTAMP(),
    target.IS_CURRENT = FALSE

WHEN NOT MATCHED THEN INSERT (
    RESTAURANT_HK, RESTAURANT_ID, NAME, CUISINE_TYPE, PRICING_FOR_TWO,
    RESTAURANT_PHONE, OPERATING_HOURS, LOCATION_ID_FK,
    ACTIVE_FLAG, OPEN_STATUS, LOCALITY, RESTAURANT_ADDRESS,
    LATITUDE, LONGITUDE, EFF_START_DATE, EFF_END_DATE, IS_CURRENT
)
VALUES (
    HASH(SHA1_HEX(CONCAT(
        source.RESTAURANT_ID, source.NAME, source.CUISINE_TYPE,
        source.PRICING_FOR_TWO, source.RESTAURANT_PHONE,
        source.OPERATING_HOURS, source.LOCATION_ID_FK,
        source.ACTIVE_FLAG, source.OPEN_STATUS,
        source.LOCALITY, source.RESTAURANT_ADDRESS,
        source.LATITUDE, source.LONGITUDE
    ))),
    source.RESTAURANT_ID, source.NAME, source.CUISINE_TYPE, source.PRICING_FOR_TWO,
    source.RESTAURANT_PHONE, source.OPERATING_HOURS, source.LOCATION_ID_FK,
    source.ACTIVE_FLAG, source.OPEN_STATUS, source.LOCALITY, source.RESTAURANT_ADDRESS,
    source.LATITUDE, source.LONGITUDE,
    CURRENT_TIMESTAMP(), NULL, TRUE
);


ALTER TASK STAGE_SCH.RESTAURANT_DQ_TASK RESUME;
ALTER TASK STAGE_SCH.RESTAURANT_TRANSFORM_TASK RESUME;
ALTER TASK CLEAN_SCH.RESTAURANT_DIM_TASK RESUME;

ALTER PIPE STAGE_SCH.RESTAURANT_PIPE REFRESH;

